### ISSUE TITLE
Installation currently fails

### ISSUE THREAD

**Issue by mattsches** [clue/framework-x#6] opened 2021-06-21 10:00 UTC
Hi Christian,

I hope this is the correct place for reporting issues ;)

I've just had an idea for a small script and tried to install framework-x, but it currently fails with:

```bash
$ php -v
PHP 8.0.7 (cli) (built: Jun  4 2021 21:26:29) ( NTS )

$ composer --version
Composer version 2.1.3 2021-06-09 16:31:20

$ composer require clue/framework-x:dev-main
./composer.json has been updated
Running composer update clue/framework-x
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires clue/framework-x dev-main -> satisfiable by clue/framework-x[dev-main].
    - clue/framework-x dev-main requires react/event-loop dev-master#1a709e2 as 1.2.0 -> found react/event-loop[dev-master] but it does not match your minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```

If I set `minimum-stability` to `dev`:

```bash
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - clue/framework-x dev-main requires react/http ^1.1 -> satisfiable by react/http[v1.1.0, v1.2.0, v1.3.0].
    - react/http[v1.1.0, ..., v1.3.0] require react/event-loop ^1.0 || ^0.5 -> satisfiable by react/event-loop[v0.5.0, v0.5.1, v0.5.2, v0.5.3, v1.0.0, v1.1.0, v1.1.1].
    - You can only install one version of a package, so only one of these can be installed: react/event-loop[dev-master, v0.3.0, ..., v0.5.3, v1.0.0, v1.1.0, v1.1.1].
    - clue/framework-x dev-main requires react/event-loop dev-master#1a709e2 as 1.2.0 -> satisfiable by react/event-loop[dev-master].
    - Root composer.json requires clue/framework-x dev-main -> satisfiable by clue/framework-x[dev-main].

```

**Comment by clue** [comment] 2021-06-21 14:05
@mattsches Thank you for bringing this up, I can indeed confirm this!

The temporary work-around is to install it like this:

```bash
$ composer require "clue/framework-x:dev-main" "react/event-loop:dev-master#1a709e2 as 1.2.0"
```

This is caused by https://github.com/clue-access/framework-x/pull/22 that has been merged last Friday. This currently builds on top of https://github.com/reactphp/event-loop/pull/226 which is currently untagged, so this temporarily references its `master` branch. This will be released very soon, at which point we'll be able to target the `v1.2.0` version instead :+1: 

I believe this has been answered with the above work-around, but I'll leave this ticket open for the reference. I'll make sure to get the release out as soon as possible and will update this ticket accordingly :+1:

**Comment by clue** [comment] 2021-07-12 20:14
This has just been fixed via https://github.com/clue-access/framework-x/pull/29 (in @clue-access) :shipit: 

Installation should now work as usual, so if you've installed during this period, you may want to remove your explicit dependency on an unstable EventLoop version again.

**Closed by clue** 2021-07-12 20:14 UTC
Labels: bug, question
